# -*- coding: utf-8 -*-
"""main project 2(A).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oX-jVVz_kYRafWVCQuW3jn1ICwxvYNdv
"""

# ============================================================
# STEP 1: IMPORT LIBRARIES
# ============================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import joblib
import warnings

warnings.filterwarnings("ignore")


from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score)
from xgboost import XGBRegressor
from statsmodels.tsa.arima.model import ARIMA
from prophet import Prophet
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import (
    LSTM,
    Dense,
    Dropout)
from tensorflow.keras.callbacks import EarlyStopping

# ============================================================
# STEP 2: LOAD DATASET
# ============================================================

df = pd.read_excel("/content/Sales_Forcasting_Dataset.xlsx")


print("Dataset Loaded Successfully!")

# ============================================================
# STEP 4: DATASET UNDERSTANDING
# ============================================================

print("\n================================")
print("DATASET SHAPE")
print("================================")

print(df.shape)


print("\n================================")
print("FIRST 5 ROWS")
print("================================")

print(df.head())


print("\n================================")
print("COLUMN NAMES")
print("================================")

print(df.columns.tolist())


print("\n================================")
print("DATA TYPES")
print("================================")

print(df.dtypes)


print("\n================================")
print("DATASET INFO")
print("================================")

df.info()


print("\n================================")
print("STATISTICAL SUMMARY")
print("================================")

print(df.describe(include="all"))

# ============================================================
# STEP 3: MISSING VALUES
# ============================================================

print("\n================================")
print("MISSING VALUES")
print("================================")

print(df.isnull().sum())

# ============================================================
# STEP 4: DUPLICATES
# ============================================================

print("\nDuplicate Rows:")

print(df.duplicated().sum())
df = (df.drop_duplicates().copy())
print("Shape after duplicate removal:",df.shape)

# ============================================================
# STEP 5: DATE CONVERSION
# ============================================================

df["Date"] = pd.to_datetime(
    df["Date"],
    errors="coerce")
df = (df.dropna(subset=["Date"]))
df = (
    df
    .sort_values("Date")
    .reset_index(drop=True))
print("\nDate conversion completed!")

# ============================================================
# STEP 6: HANDLE MISSING VALUES
# ============================================================

numeric_columns = (df.select_dtypes(
        include=np.number).columns.tolist())

categorical_columns = (df.select_dtypes(include=
         ["object","category"]).columns.tolist())


for column in numeric_columns:

    df[column] = (df[column].fillna(df[column].median()))

for column in categorical_columns:

    df[column] = (df[column].fillna("Unknown"))


print(
    "\nRemaining Missing Values:",
    df.isnull().sum().sum())

# ============================================================
# STEP 7: UNIVARIATE ANALYSIS
# ============================================================

print("\n================================")
print("UNIVARIATE ANALYSIS")
print("================================")


numeric_columns = (

    df
    .select_dtypes(
        include=np.number
    )
    .columns
    .tolist()

)


print(
    df[numeric_columns].describe()
)


# ---------------- NUMERIC HISTOGRAM ----------------

for column in numeric_columns:

    plt.figure(
        figsize=(8, 4)
    )

    sns.histplot(
        data=df,
        x=column,
        bins=30,
        kde=True
    )

    plt.title(
        f"Distribution of {column}"
    )

    plt.show()


# ---------------- BOXPLOT ----------------

for column in numeric_columns:

    plt.figure(
        figsize=(8, 3)
    )

    sns.boxplot(
        x=df[column]
    )

    plt.title(
        f"Boxplot of {column}"
    )

    plt.show()


# ---------------- CATEGORICAL ----------------

categorical_columns = (

    df
    .select_dtypes(
        include=[
            "object",
            "category"
        ]
    )
    .columns
    .tolist()

)


for column in categorical_columns:

    print(
        f"\n{column}"
    )

    print(
        df[column]
        .value_counts()
        .head(20)
    )


    if df[column].nunique() <= 20:

        plt.figure(
            figsize=(10, 5)
        )

        sns.countplot(
            data=df,
            x=column
        )

        plt.title(
            f"Count Plot - {column}"
        )

        plt.xticks(
            rotation=45
        )

        plt.show()

# ============================================================
# STEP 8: BIVARIATE ANALYSIS
# ============================================================

print("\n================================")
print("BIVARIATE ANALYSIS")
print("================================")


bivariate_columns = [

    "Price",

    "Discount_Percentage",

    "Marketing_Spend",

    "Stock_Availability",

    "Competitor_Price"]


for column in bivariate_columns:

    if column in df.columns:

        plt.figure(
            figsize=(8, 5))

        sns.scatterplot(
            data=df,
            x=column,
            y="Units_Sold")

        plt.title(
            f"{column} vs Units Sold"
        )

        plt.show()


# Category vs Units Sold

if "Category" in df.columns:

    plt.figure(
        figsize=(10, 5)
    )

    sns.boxplot(
        data=df,
        x="Category",
        y="Units_Sold"
    )

    plt.xticks(
        rotation=45
    )

    plt.title(
        "Category vs Units Sold"
    )

    plt.show()


# Promotion vs Units Sold

if "Promotion_Flag" in df.columns:

    plt.figure(
        figsize=(8, 5)
    )

    sns.boxplot(
        data=df,
        x="Promotion_Flag",
        y="Units_Sold"
    )

    plt.title(
        "Promotion vs Units Sold"
    )

    plt.show()

# ============================================================
# STEP 9: MULTIVARIATE ANALYSIS
# ============================================================

print("\n================================")
print("MULTIVARIATE ANALYSIS")
print("================================")


numeric_df = (

    df
    .select_dtypes(
        include=np.number
    )

)


correlation = (
    numeric_df
    .corr()
)


plt.figure(
    figsize=(16, 12)
)


sns.heatmap(
    correlation,
    cmap="coolwarm",
    center=0
)


plt.title(
    "Correlation Heatmap"
)


plt.show()


print(
    "\nCorrelation with Units Sold:"
)


print(

    correlation[
        "Units_Sold"
    ]

    .sort_values(
        ascending=False
    )

)

# ============================================================
# STEP 10: OUTLIER DETECTION
# ============================================================

print("\n================================")
print("OUTLIER DETECTION")
print("================================")


outlier_report = []


for column in numeric_columns:

    Q1 = (
        df[column]
        .quantile(0.25)
    )

    Q3 = (
        df[column]
        .quantile(0.75)
    )


    IQR = Q3 - Q1


    lower_limit = (
        Q1
        -
        1.5 * IQR
    )


    upper_limit = (
        Q3
        +
        1.5 * IQR
    )


    outliers = df[

        (df[column] < lower_limit)

        |

        (df[column] > upper_limit)

    ]


    outlier_report.append({

        "Column":
            column,

        "Q1":
            Q1,

        "Q3":
            Q3,

        "IQR":
            IQR,

        "Lower_Limit":
            lower_limit,

        "Upper_Limit":
            upper_limit,

        "Outlier_Count":
            len(outliers)

    })


outlier_report_df = pd.DataFrame(
    outlier_report
)


print(
    outlier_report_df
)

# ============================================================
# STEP 11: FEATURE ENGINEERING FOR XGBOOST
# ============================================================

df_features = df.copy()


# ---------------- DATE FEATURES ----------------

df_features["Year"] = (
    df_features["Date"].dt.year
)


df_features["Month_Number"] = (
    df_features["Date"].dt.month
)


df_features["Day"] = (
    df_features["Date"].dt.day
)


df_features["DayOfYear"] = (
    df_features["Date"].dt.dayofyear
)


df_features["WeekOfYear"] = (

    df_features["Date"]

    .dt.isocalendar()

    .week

    .astype(int)

)


df_features["DayOfWeek_Number"] = (
    df_features["Date"].dt.dayofweek
)


# ---------------- INTERACTION FEATURES ----------------

df_features["Pricing_Effect"] = (

    df_features["Price"]

    *

    df_features[
        "Discount_Percentage"
    ]

)


df_features["Promotion_Effect"] = (

    df_features[
        "Marketing_Spend"
    ]

    *

    df_features[
        "Promotion_Flag"
    ]

)


df_features["Inventory_Value"] = (

    df_features[
        "Stock_Availability"
    ]

    *

    df_features["Price"]

)


df_features["Seasonal_Effect"] = (

    df_features[
        "Promotion_Flag"
    ]

    *

    df_features[
        "Holiday_Flag"
    ]

)


df_features["Price_Difference"] = (

    df_features["Price"]

    -

    df_features[
        "Competitor_Price"
    ]

)


df_features["Discounted_Price"] = (

    df_features["Price"]

    *

    (

        1

        -

        df_features[
            "Discount_Percentage"
        ] / 100

    )

)

# ============================================================
# STEP 12: X AND Y
# ============================================================

# Revenue removed because it may leak Units_Sold information.

X = df_features.drop(

    columns=[

        "Units_Sold",

        "Revenue",

        "Row_ID",

        "Date"

    ],

    errors="ignore"

)


y = df_features[
    "Units_Sold"
]

# ============================================================
# STEP 13: ENCODING
# ============================================================

categorical_columns = (

    X
    .select_dtypes(
        include=[
            "object",
            "category"
        ]
    )
    .columns
    .tolist()

)


label_encoders = {}


for column in categorical_columns:

    le = LabelEncoder()


    X[column] = le.fit_transform(

        X[column]
        .astype(str)

    )


    label_encoders[column] = le

# ============================================================
# STEP 14: FINAL CLEANING
# ============================================================

X = X.replace(

    [np.inf, -np.inf],

    np.nan

)


for column in X.columns:

    if X[column].isnull().sum() > 0:

        X[column] = (

            X[column]

            .fillna(
                X[column].median()
            )

        )

# ============================================================
# STEP 15: TRAIN / VALIDATION / TEST SPLIT
# ============================================================

total_rows = len(X)


train_end = int(
    total_rows * 0.70
)


validation_end = int(
    total_rows * 0.85
)


X_train = X.iloc[
    :train_end
]


y_train = y.iloc[
    :train_end
]


X_validation = X.iloc[
    train_end:
    validation_end
]


y_validation = y.iloc[
    train_end:
    validation_end
]


X_test = X.iloc[
    validation_end:
]


y_test = y.iloc[
    validation_end:
]


print("\n================================")
print("DATA SPLIT")
print("================================")


print(
    "Train:",
    X_train.shape
)


print(
    "Validation:",
    X_validation.shape
)


print(
    "Test:",
    X_test.shape
)


# ============================================================
# FUNCTION-FREE METRIC STORAGE
# ============================================================

model_results = []

# ============================================================
# STEP 16: XGBOOST MODEL
# ============================================================

print("\n================================")
print("XGBOOST")
print("================================")


xgb_model = XGBRegressor(

    n_estimators=800,

    learning_rate=0.03,

    max_depth=7,

    min_child_weight=2,

    subsample=0.9,

    colsample_bytree=0.9,

    reg_alpha=0.05,

    reg_lambda=1.0,

    objective="reg:squarederror",

    random_state=42,

    n_jobs=-1

)


xgb_model.fit(

    X_train,

    y_train

)


xgb_pred = xgb_model.predict(
    X_test
)


xgb_pred = np.maximum(
    xgb_pred,
    0
)


# XGBoost MAE

xgb_mae = mean_absolute_error(

    y_test,

    xgb_pred

)


# XGBoost RMSE

xgb_rmse = np.sqrt(

    mean_squared_error(

        y_test,

        xgb_pred

    )

)


# XGBoost R2

xgb_r2 = r2_score(

    y_test,

    xgb_pred

)


# XGBoost MAPE

actual_xgb = (
    y_test.values
)


non_zero = (
    actual_xgb != 0
)

xgb_mape = np.mean(

    np.abs(

        (

            actual_xgb[non_zero]

            -

            xgb_pred[non_zero]

        )

        /

        actual_xgb[non_zero]

    )

) * 100


# XGBoost SMAPE

denominator = (

    np.abs(actual_xgb)

    +

    np.abs(xgb_pred)

)


valid = (
    denominator != 0
)

xgb_smape = (

    np.mean(

        2

        *

        np.abs(

            xgb_pred[valid]

            -

            actual_xgb[valid]

        )

        /

        denominator[valid]

    )

    * 100

)


model_results.append({

    "Model":
        "XGBoost",

    "MAE":
        xgb_mae,

    "RMSE":
        xgb_rmse,

    "R2":
        xgb_r2,

    "MAPE":
        xgb_mape,

    "SMAPE":
        xgb_smape

})


print(
    "XGBoost completed!"
)

# ============================================================
# STEP 17: PREPARE TIME SERIES DATA
# ============================================================

# For ARIMA, Prophet and LSTM,
# create one total Units_Sold value per Date.

time_series_df = (

    df[
        [
            "Date",
            "Units_Sold"
        ]
    ]

    .groupby(
        "Date",
        as_index=False
    )

    ["Units_Sold"]

    .sum()

    .sort_values(
        "Date"
    )

    .reset_index(
        drop=True
    )

)


print("\nTime Series Shape:")

print(
    time_series_df.shape
)


print(
    time_series_df.head()
)

# ============================================================
# STEP 18: TIME SERIES TRAIN / VALIDATION / TEST
# ============================================================

ts_total = len(
    time_series_df
)


ts_train_end = int(
    ts_total * 0.70
)


ts_validation_end = int(
    ts_total * 0.85
)


ts_train = time_series_df.iloc[
    :ts_train_end
]


ts_validation = time_series_df.iloc[
    ts_train_end:
    ts_validation_end
]


ts_test = time_series_df.iloc[
    ts_validation_end:
]


# Train + Validation will be used for final forecast

ts_train_final = time_series_df.iloc[
    :ts_validation_end
]


ts_actual = (

    ts_test[
        "Units_Sold"
    ]

    .values

)


forecast_steps = len(
    ts_test
)


print(
    "\nTime-series forecast steps:",
    forecast_steps
)

# ============================================================
# STEP 19: ARIMA MODEL
# ============================================================

print("\n================================")
print("ARIMA MODEL")
print("================================")


arima_model = ARIMA(

    ts_train_final[
        "Units_Sold"
    ],

    order=(5, 1, 2)

)


arima_fit = arima_model.fit()


arima_pred = arima_fit.forecast(

    steps=forecast_steps

)


arima_pred = np.array(
    arima_pred
)


arima_pred = np.maximum(

    arima_pred,

    0

)


# ARIMA METRICS

arima_mae = mean_absolute_error(

    ts_actual,

    arima_pred

)


arima_rmse = np.sqrt(

    mean_squared_error(

        ts_actual,

        arima_pred

    )

)


arima_r2 = r2_score(

    ts_actual,

    arima_pred

)


non_zero = (
    ts_actual != 0
)

arima_mape = np.mean(

    np.abs(

        (

            ts_actual[non_zero]

            -

            arima_pred[non_zero]

        )

        /

        ts_actual[non_zero]

    )

) * 100


denominator = (

    np.abs(ts_actual)

    +

    np.abs(arima_pred)

)


valid = (
    denominator != 0
)

arima_smape = (

    np.mean(

        2

        *

        np.abs(

            arima_pred[valid]

            -

            ts_actual[valid]

        )

        /

        denominator[valid]

    )

    * 100

)


model_results.append({

    "Model":
        "ARIMA",

    "MAE":
        arima_mae,

    "RMSE":
        arima_rmse,

    "R2":
        arima_r2,

    "MAPE":
        arima_mape,

    "SMAPE":
        arima_smape

})


print(
    "ARIMA completed!"
)

# ============================================================
# STEP 20: PROPHET MODEL
# ============================================================

print("\n================================")
print("PROPHET MODEL")
print("================================")


prophet_train = (

    ts_train_final[
        [
            "Date",
            "Units_Sold"
        ]
    ]

    .copy()

)


prophet_train.columns = [

    "ds",

    "y"

]


prophet_model = Prophet(

    yearly_seasonality=True,

    weekly_seasonality=True,

    daily_seasonality=False,

    changepoint_prior_scale=0.05,

    seasonality_prior_scale=10

)


prophet_model.fit(
    prophet_train
)


prophet_future = pd.DataFrame({

    "ds":
        ts_test["Date"].values

})


prophet_forecast = prophet_model.predict(

    prophet_future

)


prophet_pred = (

    prophet_forecast[
        "yhat"
    ]

    .values

)


prophet_pred = np.maximum(

    prophet_pred,

    0

)


# Prophet metrics

prophet_mae = mean_absolute_error(

    ts_actual,

    prophet_pred

)


prophet_rmse = np.sqrt(

    mean_squared_error(

        ts_actual,

        prophet_pred

    )

)


prophet_r2 = r2_score(

    ts_actual,

    prophet_pred

)


non_zero = (
    ts_actual != 0
)


prophet_mape = np.mean(

    np.abs(

        (

            ts_actual[non_zero]

            -

            prophet_pred[non_zero]

        )

        /

        ts_actual[non_zero]

    )

) * 100


denominator = (

    np.abs(ts_actual)

    +

    np.abs(prophet_pred)

)


valid = denominator != 0


prophet_smape = (

    np.mean(

        2

        *

        np.abs(

            prophet_pred[valid]

            -

            ts_actual[valid]

        )

        /

        denominator[valid]

    )

    * 100

)


model_results.append({

    "Model":
        "Prophet",

    "MAE":
        prophet_mae,

    "RMSE":
        prophet_rmse,

    "R2":
        prophet_r2,

    "MAPE":
        prophet_mape,

    "SMAPE":
        prophet_smape

})


print(
    "Prophet completed!"
)

# ============================================================
# STEP 21: LSTM PREPARATION
# ============================================================

print("\n================================")
print("LSTM MODEL")
print("================================")


lstm_sales = (

    time_series_df[
        "Units_Sold"
    ]

    .values

    .reshape(-1, 1)

)


lstm_scaler = MinMaxScaler()


# Fit scaler only using data before test period

lstm_scaler.fit(

    lstm_sales[
        :ts_validation_end
    ]

)


sales_scaled = (

    lstm_scaler
    .transform(
        lstm_sales
    )

)


# Number of previous days used to predict next day

sequence_length = 30


X_lstm = []

y_lstm = []


# Create sequences only until test boundary

for i in range(

    sequence_length,

    ts_validation_end

):

    X_lstm.append(

        sales_scaled[

            i - sequence_length:
            i,

            0

        ]

    )


    y_lstm.append(

        sales_scaled[
            i,
            0
        ]

    )


X_lstm = np.array(
    X_lstm
)


y_lstm = np.array(
    y_lstm
)


X_lstm = X_lstm.reshape(

    X_lstm.shape[0],

    X_lstm.shape[1],

    1

)


print(
    "LSTM X Shape:",
    X_lstm.shape
)


print(
    "LSTM y Shape:",
    y_lstm.shape
)

# ============================================================
# STEP 22: BUILD LSTM MODEL
# ============================================================

lstm_model = Sequential()


lstm_model.add(

    LSTM(

        64,

        return_sequences=True,

        input_shape=(
            sequence_length,
            1
        )

    )

)


lstm_model.add(

    Dropout(0.2)

)


lstm_model.add(

    LSTM(
        32
    )

)


lstm_model.add(

    Dropout(0.2)

)


lstm_model.add(

    Dense(
        16,
        activation="relu"
    )

)


lstm_model.add(

    Dense(1)

)


lstm_model.compile(

    optimizer="adam",

    loss="mse"

)


early_stop = EarlyStopping(

    monitor="val_loss",

    patience=10,

    restore_best_weights=True

)

# ============================================================
# STEP 23: TRAIN LSTM
# ============================================================

history = lstm_model.fit(

    X_lstm,

    y_lstm,

    epochs=100,

    batch_size=32,

    validation_split=0.15,

    callbacks=[
        early_stop
    ],

    verbose=1,

    shuffle=False

)

# ============================================================
# STEP 24: LSTM TEST FORECAST
# ============================================================

lstm_predictions_scaled = []


current_sequence = (

    sales_scaled[

        ts_validation_end
        -
        sequence_length:
        ts_validation_end

    ]

    .reshape(
        sequence_length,
        1
    )

)


for i in range(
    forecast_steps
):

    input_sequence = (

        current_sequence

        .reshape(
            1,
            sequence_length,
            1
        )

    )


    next_prediction = (

        lstm_model

        .predict(
            input_sequence,
            verbose=0
        )

        [0][0]

    )


    lstm_predictions_scaled.append(

        next_prediction

    )


    current_sequence = np.vstack([

        current_sequence[1:],

        [[next_prediction]]

    ])


lstm_predictions_scaled = (

    np.array(
        lstm_predictions_scaled
    )

    .reshape(-1, 1)

)


lstm_pred = (

    lstm_scaler

    .inverse_transform(
        lstm_predictions_scaled
    )

    .flatten()

)


lstm_pred = np.maximum(

    lstm_pred,

    0

)

# ============================================================
# STEP 25: LSTM METRICS
# ============================================================

lstm_mae = mean_absolute_error(

    ts_actual,

    lstm_pred

)


lstm_rmse = np.sqrt(

    mean_squared_error(

        ts_actual,

        lstm_pred

    )

)


lstm_r2 = r2_score(

    ts_actual,

    lstm_pred

)


non_zero = (
    ts_actual != 0
)

lstm_mape = np.mean(

    np.abs(

        (

            ts_actual[non_zero]

            -

            lstm_pred[non_zero]

        )

        /

        ts_actual[non_zero]

    )

) * 100


denominator = (

    np.abs(ts_actual)

    +

    np.abs(lstm_pred)

)


valid = (
    denominator != 0
)

lstm_smape = (

    np.mean(

        2

        *

        np.abs(

            lstm_pred[valid]

            -

            ts_actual[valid]

        )

        /

        denominator[valid]

    )

    * 100

)


model_results.append({

    "Model":
        "LSTM",

    "MAE":
        lstm_mae,

    "RMSE":
        lstm_rmse,

    "R2":
        lstm_r2,

    "MAPE":
        lstm_mape,

    "SMAPE":
        lstm_smape

})


print(
    "LSTM completed!"
)

# ============================================================
# STEP 26: MODEL COMPARISON
# ============================================================

comparison_df = pd.DataFrame(

    model_results

)


comparison_df = (

    comparison_df

    .sort_values(

        by="RMSE",

        ascending=True

    )

    .reset_index(
        drop=True
    )

)


print("\n==========================================")
print("FINAL MODEL COMPARISON")
print("==========================================")


print(

    comparison_df

    .round(4)

)

# ============================================================
# STEP 27: DISPLAY BEST MODEL
# ============================================================

best_model = (

    comparison_df

    .iloc[0]

)


print("\n==========================================")
print("BEST MODEL")
print("==========================================")


print(

    "Model:",

    best_model["Model"]

)


print(

    "MAE:",

    round(
        best_model["MAE"],
        4
    )

)


print(

    "RMSE:",

    round(
        best_model["RMSE"],
        4
    )

)


print(

    "R2:",

    round(
        best_model["R2"],
        4
    )

)


print(

    "MAPE:",

    round(
        best_model["MAPE"],
        2
    ),

    "%"

)


print(

    "SMAPE:",

    round(
        best_model["SMAPE"],
        2
    ),

    "%"

)

# ============================================================
# STEP 28: MODEL COMPARISON - R2 GRAPH
# ============================================================

plt.figure(
    figsize=(8, 5)
)


plt.bar(

    comparison_df["Model"],

    comparison_df["R2"]

)


plt.xlabel(
    "Model"
)


plt.ylabel(
    "R2 Score"
)


plt.title(
    "Model Comparison - R2"
)


plt.show()

# ============================================================
# STEP 29: XGBOOST ACTUAL VS PREDICTED
# ============================================================

plt.figure(
    figsize=(12, 6)
)


plt.plot(

    y_test.values,

    label="Actual"

)


plt.plot(

    xgb_pred,

    label="XGBoost Prediction"

)


plt.xlabel(
    "Test Records"
)


plt.ylabel(
    "Units Sold"
)


plt.title(
    "XGBoost - Actual vs Predicted"
)


plt.legend()


plt.show()

# ============================================================
# STEP 30: XGBOOST FEATURE IMPORTANCE
# ============================================================

feature_importance = pd.DataFrame({

    "Feature":
        X.columns,

    "Importance":
        xgb_model.feature_importances_

})


feature_importance = (

    feature_importance

    .sort_values(

        "Importance",

        ascending=False

    )

)


print(
    "\nTop 20 Features:"
)


print(

    feature_importance

    .head(20)

)


top_features = (

    feature_importance

    .head(20)

    .sort_values(
        "Importance"
    )

)


plt.figure(
    figsize=(10, 8)
)


plt.barh(

    top_features["Feature"],

    top_features["Importance"]

)


plt.xlabel(
    "Importance"
)


plt.ylabel(
    "Feature"
)


plt.title(
    "XGBoost Feature Importance"
)


plt.show()

import joblib

# ============================================================
# STEP 31: SAVE MODELS AND ARTIFACTS
# ============================================================

model_artifacts = {
    'xgb_model': xgb_model,
    'label_encoders': label_encoders,
    'model_features': X.columns.tolist()
}

joblib.dump(model_artifacts, "xgboost_sales_model_artifacts.pkl")

print("XGBoost model and preprocessing artifacts saved as 'xgboost_sales_model_artifacts.pkl'")